export const fakeLeadsData = [
  {
    name: "Ralph Edwards",
    leadStatus: "Need Contact Details",
    leadOwner: "Plabon",
    mobile: "",
    email: "ralphedwards@email.com",
    createdOn: "2025-06-25T12:56:00", // assuming today is June 25
    score: null,
    purchaseCompanyName: "COMPASS",
    stage: "Lead Received",
  },
  {
    name: "Ronald Richards",
    leadStatus: "Need Contact Details",
    leadOwner: "Plabon",
    mobile: "(229) 529-7238",
    email: "",
    createdOn: "2025-06-24T15:56:00",
    score: null,
    purchaseCompanyName: "Openrent",
    stage: "Lead Received",
  },
  {
    name: "Lucas Arlene",
    leadStatus: "Going Cold",
    leadOwner: "Plabon",
    mobile: "(316) 578-8293",
    email: "lucasa@email.com",
    recentActivity: "Yesterday 2:39 PM",
    createdOn: "2025-06-24T14:39:00",
    score: null,
    purchaseCompanyName: "Apartments.com",
    stage: "Lead Received",
  },
  {
    name: "Savannah Andrea",
    leadStatus: "Going Cold",
    leadOwner: "Plabon",
    mobile: "",
    email: "",
    createdOn: "2025-06-24T13:02:00",
    score: null,
    purchaseCompanyName: "",
    stage: "Lead Received",
  },
  {
    name: "Cameron Gilson",
    leadStatus: "Going Cold",
    leadOwner: "Plabon",
    mobile: "(702) 566-5172",
    email: "camerongil@email.com",
    createdOn: "2025-06-25T09:23:00",
    score: null,
    purchaseCompanyName: "Apartments.com",
    stage: "Tour Scheduled",
  },
  {
    name: "Marvin McKinney",
    leadStatus: "Need Follow Up",
    leadOwner: "Plabon",
    mobile: "(684) 555-9230",
    email: "marvinmc@email.com",
    createdOn: "2025-06-24T14:39:00",
    score: null,
    purchaseCompanyName: "Zillow",
    stage: "Tour Scheduled",
  },
  {
    name: "Jane Cooper",
    leadStatus: "Need Follow Up",
    leadOwner: "Plabon",
    mobile: "(702) 566-5172",
    email: "janecooper@email.com",
    createdOn: "2025-06-24T09:23:00",
    score: null,
    purchaseCompanyName: "Apartments.com",
    stage: "Tour Scheduled",
  },
  {
    name: "Brooklyn Simmons",
    leadStatus: "Going Cold",
    leadOwner: "Plabon",
    mobile: "",
    email: "",
    createdOn: "2025-06-24T09:05:00",
    score: null,
    purchaseCompanyName: "",
    stage: "Tour Scheduled",
  },
  {
    name: "Eleanor Pena",
    leadStatus: "Need Follow Up",
    leadOwner: "Plabon",
    mobile: "(704) 592-0627",
    email: "elepena@email.com",
    createdOn: "2025-06-25T10:49:00",
    score: null,
    purchaseCompanyName: "Zillow",
    stage: "Application Received",
  },
  {
    name: "Andrew Cody",
    leadStatus: "Fast Response",
    leadOwner: "Plabon",
    mobile: "(252) 543-0627",
    email: "andrewcd@email.com",
    createdOn: "2025-06-24T16:23:00",
    score: null,
    purchaseCompanyName: "trulia",
    stage: "Application Received",
  },
  {
    name: "Robert Fox",
    leadStatus: "Fast Response",
    leadOwner: "Plabon",
    mobile: "(702) 566-5172",
    email: "robertfox@email.com",
    createdOn: "2025-06-24T16:05:00",
    score: null,
    purchaseCompanyName: "trulia",
    stage: "Application Received",
  },
  {
    name: "Robert Hawkins",
    leadStatus: "Fast Response",
    leadOwner: "Plabon",
    mobile: "(270) 685-0957",
    email: "roberth@email.com",
    createdOn: "2025-06-25T14:38:00",
    score: null,
    purchaseCompanyName: "Openrent",
    stage: "Application Approved",
  },
  {
    name: "Annette Cute",
    leadStatus: "Need Follow Up",
    leadOwner: "Plabon",
    mobile: "(302) 566-9823",
    email: "annettecute@email.com",
    createdOn: "2025-06-24T16:23:00",
    score: null,
    purchaseCompanyName: "Zillow",
    stage: "Application Approved",
  },
];
