
export const fakeLeadsData = [
  
  {
    name: "Amina Al-Hassan",
    status: "Contacted",
    leadOwner: "Plabon",
    mobile: "544444444",
    email: "amina.h@gmail.com",
    recentActivity: "Requested Info",
    createdOn: "2025-06-09T09:15:00",
    score: 73,
    purchaseCompanyName: "Zillow",
    typeOfAction: "Lead Contacted"
  },
  {
    name: "Khalid ibn Saeed",
    status: "New Lead",
    leadOwner: "Sasanka",
    mobile: "555555555",
    email: "khalid.s@example.com",
    recentActivity: "Clicked Email",
    createdOn: "2025-06-11T12:45:00",
    score: 66,
    purchaseCompanyName: "Openrent",
    typeOfAction: "Lead Received"
  },
  {
    name: "Fatima Noor",
    status: "Qualified",
    leadOwner: "Rashed",
    mobile: "566666666",
    email: "fatima.n@gmail.com",
    recentActivity: "Phone Call",
    createdOn: "2025-06-12T16:00:00",
    score: 91,
    purchaseCompanyName: "apartments.com",
    typeOfAction: "Lead Qualified"
  },
  {
    name: "Yasir Qadhi",
    status: "Contacted",
    leadOwner: "Sana",
    mobile: "577777777",
    email: "yasir.q@example.com",
    recentActivity: "Followed Up",
    createdOn: "2025-06-13T10:10:00",
    score: 58,
    purchaseCompanyName: "Trulia",
    typeOfAction: "Lead Contacted"
  },
  {
    name: "Zayn Malik",
    status: "New Lead",
    leadOwner: "Sasanka",
    mobile: "588888888",
    email: "zayn.m@gmail.com",
    recentActivity: "Form Submitted",
    createdOn: "2025-06-14T11:30:00",
    score: 79,
    purchaseCompanyName: "Compass",
    typeOfAction: "Lead Received"
  },
  {
    name: "Layla Hassan",
    status: "Qualified",
    leadOwner: "Plabon",
    mobile: "599999999",
    email: "layla.h@example.com",
    recentActivity: "Email Opened",
    createdOn: "2025-06-15T08:20:00",
    score: 85,
    purchaseCompanyName: "Zillow",
    typeOfAction: "Lead Qualified"
  },
  {
    name: "Umar Rauf",
    status: "New Lead",
    leadOwner: "Sana",
    mobile: "511111111",
    email: "umar.r@gmail.com",
    recentActivity: "Fast Response",
    createdOn: "2025-06-16T15:05:00",
    score: 40,
    purchaseCompanyName: "Openrent",
    typeOfAction: "Lead Received"
  },
  {
    name: "Aisha Khan",
    status: "Contacted",
    leadOwner: "Rashed",
    mobile: "522222222",
    email: "aisha.k@example.com",
    recentActivity: "Asked for Details",
    createdOn: "2025-06-17T17:25:00",
    score: 72,
    purchaseCompanyName: "apartments.com",
    typeOfAction: "Lead Contacted"
  },
  {
    name: "Bilal Ahmed",
    status: "Qualified",
    leadOwner: "Plabon",
    mobile: "533333334",
    email: "bilal.a@gmail.com",
    recentActivity: "Meeting Scheduled",
    createdOn: "2025-06-18T13:55:00",
    score: 93,
    purchaseCompanyName: "Trulia",
    typeOfAction: "Lead Qualified"
  },
  {
    name: "Salma Bint Omar",
    status: "New Lead",
    leadOwner: "Sana",
    mobile: "544444445",
    email: "salma.o@example.com",
    recentActivity: "Subscribed",
    createdOn: "2025-06-19T14:00:00",
    score: 68,
    purchaseCompanyName: "Zillow",
    typeOfAction: "Lead Received"
  },
  {
    name: "Hamza Tariq",
    status: "Contacted",
    leadOwner: "Sasanka",
    mobile: "555555556",
    email: "hamza.t@example.com",
    recentActivity: "Chat Started",
    createdOn: "2025-06-20T11:10:00",
    score: 55,
    purchaseCompanyName: "Compass",
    typeOfAction: "Lead Contacted"
  },
  {
    name: "Iman Zafar",
    status: "Qualified",
    leadOwner: "Plabon",
    mobile: "566666667",
    email: "iman.z@example.com",
    recentActivity: "Demo Attended",
    createdOn: "2025-06-21T09:40:00",
    score: 95,
    purchaseCompanyName: "apartments.com",
    typeOfAction: "Lead Qualified"
  },
  {
    name: "Yusuf Nabi",
    status: "New Lead",
    leadOwner: "Rashed",
    mobile: "577777778",
    email: "yusuf.n@gmail.com",
    recentActivity: "Clicked Ad",
    createdOn: "2025-06-22T16:50:00",
    score: 49,
    purchaseCompanyName: "Openrent",
    typeOfAction: "Lead Received"
  },
  {
    name: "Huda Ibrahim",
    status: "Contacted",
    leadOwner: "Sana",
    mobile: "588888889",
    email: "huda.i@example.com",
    recentActivity: "Email Clicked",
    createdOn: "2025-06-23T12:00:00",
    score: 61,
    purchaseCompanyName: "Trulia",
    typeOfAction: "Lead Contacted"
  },
  {
    name: "Nabil Karim",
    status: "Qualified",
    leadOwner: "Sasanka",
    mobile: "599999990",
    email: "nabil.k@example.com",
    recentActivity: "Call Back Requested",
    createdOn: "2025-06-24T18:35:00",
    score: 82,
    purchaseCompanyName: "Zillow",
    typeOfAction: "Lead Qualified"
  },
  {
    name: "Reema Shah",
    status: "New Lead",
    leadOwner: "Plabon",
    mobile: "511111112",
    email: "reema.s@gmail.com",
    recentActivity: "Submitted Inquiry",
    createdOn: "2025-06-25T08:45:00",
    score: 77,
    purchaseCompanyName: "Compass",
    typeOfAction: "Lead Received"
  },
  {
    name: "Tariq Anwar",
    status: "Contacted",
    leadOwner: "Rashed",
    mobile: "522222223",
    email: "tariq.a@example.com",
    recentActivity: "Spoke on Phone",
    createdOn: "2025-06-26T15:30:00",
    score: 63,
    purchaseCompanyName: "apartments.com",
    typeOfAction: "Lead Contacted"
  },
  {
    name: "Zara Ali",
    status: "Qualified",
    leadOwner: "Sana",
    mobile: "533333335",
    email: "zara.a@gmail.com",
    recentActivity: "Ready to Buy",
    createdOn: "2025-06-27T13:20:00",
    score: 97,
    purchaseCompanyName: "Trulia",
    typeOfAction: "Lead Qualified"
  },
  {
    name: "Omar Siddiq",
    status: "New Lead",
    leadOwner: "Sasanka",
    mobile: "544444446",
    email: "omar.s@example.com",
    recentActivity: "Form Filled",
    createdOn: "2025-06-28T10:30:00",
    score: 59,
    purchaseCompanyName: "Openrent",
    typeOfAction: "Lead Received"
  },
  {
    name: "Shuja ibn Wahb",
    status: "New Lead",
    leadOwner: "Sasanka",
    mobile: "533333333",
    email: "abc@gmail.com",
    recentActivity: "Fast Response",
    createdOn: "2025-06-10T14:30:00",
    score: 87,
    purchaseCompanyName: "Compass",
    typeOfAction: "Application Approved"
  },
];
